"""
Catálogo de produtos mais vendidos no Brasil (2025).
Fontes: TechTudo, Buscapé, Mercado Livre, Estadão, UOL Guia de Compras.
Atualizado: março/2026 com base em dados de 2025.
"""
from __future__ import annotations

from core.market.models import TopProduct

# ─── SMARTPHONES ─────────────────────────────────────────────────────────────
PHONES: list[TopProduct] = [
    TopProduct(
        model="Motorola Moto G15",
        category="smartphone",
        rank=1,
        source_label="Mercado Livre (dez/2025)",
        price_from_brl=594,
        price_to_brl=950,
        key_specs=["4 GB RAM", "Tela 6,7\" Full HD+", "Câmera 50 MP", "Helio G81 Extreme", "Bateria 5.200 mAh", "NFC"],
        tags=["moto g15", "g15"],
    ),
    TopProduct(
        model="Samsung Galaxy A16 4G",
        category="smartphone",
        rank=2,
        source_label="Mercado Livre (dez/2025)",
        price_from_brl=785,
        price_to_brl=1300,
        key_specs=["Tela AMOLED Full HD+", "Câmera 50 MP", "NFC", "4 GB RAM", "Bateria 5.000 mAh"],
        tags=["galaxy a16", "a16"],
    ),
    TopProduct(
        model="Motorola Moto G05",
        category="smartphone",
        rank=3,
        source_label="Mercado Livre (dez/2025)",
        price_from_brl=719,
        price_to_brl=1100,
        key_specs=["Helio G81 (2,0 GHz)", "4 GB RAM", "Câmera 50 MP", "Bateria 5.200 mAh"],
        tags=["moto g05", "g05"],
    ),
    TopProduct(
        model="Xiaomi Redmi 15C",
        category="smartphone",
        rank=4,
        source_label="Mercado Livre (dez/2025)",
        price_from_brl=850,
        price_to_brl=1360,
        key_specs=["Bateria 6.000 mAh", "Câmera 50 MP"],
        tags=["redmi 15c", "redmi 15"],
    ),
    TopProduct(
        model="Samsung Galaxy A07",
        category="smartphone",
        rank=5,
        source_label="Mercado Livre (dez/2025)",
        price_from_brl=867,
        price_to_brl=1387,
        key_specs=["8 GB RAM", "Câmera 50 MP", "Tela 6,7\" HD+ 90 Hz", "Bateria 5.000 mAh"],
        tags=["galaxy a07", "a07"],
    ),
    TopProduct(
        model="Motorola Moto G35",
        category="smartphone",
        rank=6,
        source_label="Mercado Livre (dez/2025)",
        price_from_brl=750,
        price_to_brl=1200,
        key_specs=["4 GB RAM (RAM Boost 12 GB)", "NFC", "Câmera 50 MP", "5G", "Bateria 5.000 mAh"],
        tags=["moto g35", "g35"],
    ),
    TopProduct(
        model="Samsung Galaxy A56 5G",
        category="smartphone",
        rank=7,
        source_label="Mercado Livre (dez/2025)",
        price_from_brl=1821,
        price_to_brl=2913,
        key_specs=["Tela Super AMOLED 6,7\" 120 Hz", "8 GB RAM", "Câmera 50 MP OIS", "Exynos", "Bateria 5.000 mAh"],
        tags=["galaxy a56", "a56"],
    ),
    TopProduct(
        model="Xiaomi Redmi Note 14 4G",
        category="smartphone",
        rank=8,
        source_label="TechTudo / Mercado Livre (jan/2026)",
        price_from_brl=1036,
        price_to_brl=1650,
        key_specs=["6 GB RAM", "Câmera 108 MP", "Tela AMOLED 6,67\"", "Bateria 5.500 mAh", "IP54"],
        tags=["redmi note 14", "note 14 4g"],
    ),
    TopProduct(
        model="Realme C75",
        category="smartphone",
        rank=9,
        source_label="TechTudo / Mercado Livre (jan/2026)",
        price_from_brl=899,
        price_to_brl=1298,
        key_specs=["8 GB RAM", "256 GB", "Bateria 5.828 mAh", "NFC", "Câmera 50 MP"],
        tags=["realme c75", "c75"],
    ),
    TopProduct(
        model="Samsung Galaxy A06",
        category="smartphone",
        rank=10,
        source_label="TechTudo (jan/2026)",
        price_from_brl=687,
        price_to_brl=1100,
        key_specs=["Tela LCD 6,7\"", "Câmera 50 MP", "Bateria 5.000 mAh"],
        tags=["galaxy a06", "a06"],
    ),
]

# ─── SMART TVs ────────────────────────────────────────────────────────────────
TVS: list[TopProduct] = [
    TopProduct(
        model="Samsung QLED 4K 50\"",
        category="tv",
        rank=1,
        source_label="Ranking BR 2025",
        price_from_brl=2200,
        price_to_brl=3500,
        key_specs=["4K QLED", "Smart TV", "HDR"],
        tags=["samsung qled", "qled 50", "qled 55"],
    ),
    TopProduct(
        model="LG NanoCell 50\" 4K",
        category="tv",
        rank=2,
        source_label="Ranking BR 2025",
        price_from_brl=2298,
        price_to_brl=3200,
        key_specs=["4K NanoCell", "Smart TV", "webOS"],
        tags=["lg nanocell", "nanocell 50", "lg 50"],
    ),
    TopProduct(
        model="TCL P755 4K",
        category="tv",
        rank=3,
        source_label="Ranking BR 2025",
        price_from_brl=1699,
        price_to_brl=2800,
        key_specs=["4K", "Smart TV", "Google TV"],
        tags=["tcl p755", "tcl 4k", "tcl 50", "tcl 55"],
    ),
    TopProduct(
        model="LG OLED evo 55\"",
        category="tv",
        rank=4,
        source_label="Ranking BR 2025",
        price_from_brl=5034,
        price_to_brl=9000,
        key_specs=["OLED evo", "4K", "120 Hz", "Dolby Vision"],
        tags=["lg oled", "oled 55", "oled evo"],
    ),
    TopProduct(
        model="Samsung Neo QLED 55\"",
        category="tv",
        rank=5,
        source_label="Ranking BR 2025",
        price_from_brl=3500,
        price_to_brl=7000,
        key_specs=["Neo QLED", "4K", "120 Hz", "Mini LED"],
        tags=["neo qled", "samsung neo", "qn85", "qn90"],
    ),
]

# ─── NOTEBOOKS ────────────────────────────────────────────────────────────────
NOTEBOOKS: list[TopProduct] = [
    TopProduct(
        model="Lenovo IdeaPad Slim 3",
        category="notebook",
        rank=1,
        source_label="Amazon BR / TechTudo (2025)",
        price_from_brl=2500,
        price_to_brl=3500,
        key_specs=["Core i5", "SSD 512 GB", "DDR5", "Dolby Audio"],
        tags=["ideapad slim 3", "ideapad slim", "lenovo slim"],
    ),
    TopProduct(
        model="Dell Inspiron 15",
        category="notebook",
        rank=2,
        source_label="Amazon BR / TechTudo (2025)",
        price_from_brl=3199,
        price_to_brl=4200,
        key_specs=["Core i5 12ª geração", "SSD 512 GB", "15,6\""],
        tags=["dell inspiron 15", "inspiron 15", "inspiron i15"],
    ),
    TopProduct(
        model="Acer Aspire 5",
        category="notebook",
        rank=3,
        source_label="TechTudo (2025)",
        price_from_brl=3000,
        price_to_brl=4000,
        key_specs=["Core i5 13ª geração", "Thunderbolt 4", "SSD"],
        tags=["acer aspire 5", "aspire 5", "a515"],
    ),
    TopProduct(
        model="Samsung Galaxy Book4",
        category="notebook",
        rank=4,
        source_label="TechTudo (2025)",
        price_from_brl=3500,
        price_to_brl=4800,
        key_specs=["Core i5-1335U", "1,55 kg", "Leve e fino"],
        tags=["galaxy book4", "galaxy book 4", "samsung book"],
    ),
    TopProduct(
        model="Lenovo LOQ Gamer",
        category="notebook",
        rank=5,
        source_label="Amazon BR (2025)",
        price_from_brl=4099,
        price_to_brl=6000,
        key_specs=["Core i5-12450H", "16 GB RAM", "RTX 2050", "Gamer"],
        tags=["lenovo loq", "loq gamer", "loq 15"],
    ),
    TopProduct(
        model="Acer Nitro V15",
        category="notebook",
        rank=6,
        source_label="Amazon BR (2025)",
        price_from_brl=4500,
        price_to_brl=6500,
        key_specs=["Core i5-13420H", "RTX 3050", "Tela 144 Hz", "Gamer"],
        tags=["acer nitro", "nitro v15", "nitro 5"],
    ),
]

# ─── ÁUDIO (FONES / HEADPHONES) ───────────────────────────────────────────────
AUDIO: list[TopProduct] = [
    TopProduct(
        model="JBL Tune 520BT",
        category="audio",
        rank=1,
        source_label="TechTudo / Ranking BR (2025)",
        price_from_brl=180,
        price_to_brl=350,
        key_specs=["Bluetooth 5.3", "Até 57h bateria", "Sem fio", "Over-ear"],
        tags=["jbl tune 520", "tune 520bt", "jbl 520"],
    ),
    TopProduct(
        model="JBL Wave Buds 2",
        category="audio",
        rank=2,
        source_label="TechTudo (2025)",
        price_from_brl=266,
        price_to_brl=480,
        key_specs=["Cancelamento de ruído ativo", "Até 40h bateria", "TWS"],
        tags=["jbl wave buds", "wave buds 2"],
    ),
    TopProduct(
        model="JBL Quantum 100",
        category="audio",
        rank=3,
        source_label="Ranking BR (2025)",
        price_from_brl=176,
        price_to_brl=280,
        key_specs=["Gamer", "Over-ear", "P2 3,5mm"],
        tags=["jbl quantum 100", "quantum 100"],
    ),
    TopProduct(
        model="Sony WH-1000XM5",
        category="audio",
        rank=4,
        source_label="Ranking BR (2025)",
        price_from_brl=1800,
        price_to_brl=2800,
        key_specs=["Cancelamento de ruído líder", "Bluetooth 5.2", "Até 30h bateria"],
        tags=["sony wh1000xm5", "wh-1000xm5", "xm5"],
    ),
    TopProduct(
        model="Samsung Galaxy Buds3",
        category="audio",
        rank=5,
        source_label="Ranking BR (2025)",
        price_from_brl=700,
        price_to_brl=1200,
        key_specs=["TWS", "ANC", "Integração Galaxy AI"],
        tags=["galaxy buds3", "buds 3", "galaxy buds"],
    ),
    TopProduct(
        model="JBL Endurance Peak III",
        category="audio",
        rank=6,
        source_label="TechTudo (2025)",
        price_from_brl=350,
        price_to_brl=600,
        key_specs=["Esportivo", "Até 50h bateria", "IP68"],
        tags=["jbl endurance peak", "endurance peak iii"],
    ),
]

# ─── CONSOLES / GAMES ────────────────────────────────────────────────────────
GAMES: list[TopProduct] = [
    TopProduct(
        model="PlayStation 5 Slim Digital 1TB",
        category="games",
        rank=1,
        source_label="Buscapé (mar-abr/2025)",
        price_from_brl=3149,
        price_to_brl=3583,
        key_specs=["1 TB SSD", "4K", "120 fps", "Ray Tracing", "Edição Digital"],
        tags=["ps5 slim", "ps5 digital", "playstation 5 slim"],
    ),
    TopProduct(
        model="PlayStation 5 Pro 2TB",
        category="games",
        rank=2,
        source_label="Buscapé (2025)",
        price_from_brl=5778,
        price_to_brl=6500,
        key_specs=["2 TB SSD", "8K upscaling", "PSSR", "Topo de linha"],
        tags=["ps5 pro", "playstation 5 pro"],
    ),
    TopProduct(
        model="Xbox Series S 512GB",
        category="games",
        rank=3,
        source_label="Buscapé (2025)",
        price_from_brl=2090,
        price_to_brl=2494,
        key_specs=["512 GB SSD", "4K upscaling", "Game Pass"],
        tags=["xbox series s", "series s"],
    ),
    TopProduct(
        model="Nintendo Switch OLED 64GB",
        category="games",
        rank=4,
        source_label="Buscapé (2025)",
        price_from_brl=2129,
        price_to_brl=2500,
        key_specs=["Tela OLED 7\"", "64 GB", "Híbrido portátil/TV"],
        tags=["switch oled", "nintendo switch oled"],
    ),
    TopProduct(
        model="Nintendo Switch 2",
        category="games",
        rank=5,
        source_label="Ranking BR (2025)",
        price_from_brl=3800,
        price_to_brl=4500,
        key_specs=["4K (TV)", "DLSS", "Ray Tracing", "Híbrido"],
        tags=["switch 2", "nintendo switch 2"],
    ),
    TopProduct(
        model="Xbox Series X 1TB",
        category="games",
        rank=6,
        source_label="Buscapé (2025)",
        price_from_brl=4400,
        price_to_brl=4863,
        key_specs=["1 TB SSD", "4K 120fps", "Game Pass"],
        tags=["xbox series x", "series x"],
    ),
]

# ─── TÊNIS / SNEAKERS ────────────────────────────────────────────────────────
SNEAKERS: list[TopProduct] = [
    TopProduct(
        model="Adidas Breaknet",
        category="sneaker",
        rank=1,
        source_label="UOL Guia de Compras (2025)",
        price_from_brl=120,
        price_to_brl=350,
        key_specs=["Casual", "Lona", "Custo-benefício"],
        tags=["adidas breaknet", "breaknet"],
    ),
    TopProduct(
        model="Nike Air Force 1",
        category="sneaker",
        rank=2,
        source_label="Ranking BR (2025)",
        price_from_brl=450,
        price_to_brl=1200,
        key_specs=["Clássico", "Couro", "Casual/Streetwear"],
        tags=["air force 1", "air force one", "af1"],
    ),
    TopProduct(
        model="Nike Air Max 90",
        category="sneaker",
        rank=3,
        source_label="Ranking BR (2025)",
        price_from_brl=500,
        price_to_brl=1500,
        key_specs=["Air Max", "Cushioning", "Clássico"],
        tags=["air max 90", "airmax 90"],
    ),
    TopProduct(
        model="Air Jordan 1 High",
        category="sneaker",
        rank=4,
        source_label="Ranking BR (2025)",
        price_from_brl=800,
        price_to_brl=4000,
        key_specs=["Basketball", "Couro", "Streetwear", "Colecionável"],
        tags=["air jordan 1", "jordan 1 high", "aj1"],
    ),
    TopProduct(
        model="Adidas Ultraboost 22",
        category="sneaker",
        rank=5,
        source_label="Ranking BR (2025)",
        price_from_brl=400,
        price_to_brl=1200,
        key_specs=["Corrida", "Boost", "Conforto"],
        tags=["ultraboost", "ultra boost 22"],
    ),
    TopProduct(
        model="Nike Dunk Low",
        category="sneaker",
        rank=6,
        source_label="Ranking BR (2025)",
        price_from_brl=400,
        price_to_brl=2500,
        key_specs=["Streetwear", "Couro", "Colecionável"],
        tags=["dunk low", "nike dunk"],
    ),
    TopProduct(
        model="Olympikus Corre",
        category="sneaker",
        rank=7,
        source_label="Ranking BR (2025)",
        price_from_brl=150,
        price_to_brl=400,
        key_specs=["Nacional", "Corrida", "Custo-benefício"],
        tags=["olympikus", "olympikus corre"],
    ),
]

# ─── ELETRODOMÉSTICOS ────────────────────────────────────────────────────────
APPLIANCES: list[TopProduct] = [
    TopProduct(
        model="Air Fryer Mondial AF-31",
        category="eletrodomestico",
        rank=1,
        source_label="Mercado Livre / Amazon BR (2025)",
        price_from_brl=150,
        price_to_brl=450,
        key_specs=["3,5 L", "1500W", "Sem óleo"],
        tags=["air fryer mondial", "af-31", "air fryer"],
    ),
    TopProduct(
        model="Lavadora Brastemp 11kg",
        category="eletrodomestico",
        rank=2,
        source_label="Ranking BR (2025)",
        price_from_brl=1800,
        price_to_brl=3200,
        key_specs=["11 kg", "Carga frontal/superior", "Inverter"],
        tags=["lavadora brastemp", "brastemp 11kg", "maquina lavar brastemp"],
    ),
    TopProduct(
        model="Geladeira Consul 410L",
        category="eletrodomestico",
        rank=3,
        source_label="Ranking BR (2025)",
        price_from_brl=2200,
        price_to_brl=4000,
        key_specs=["410 L", "Frost Free", "Duplex"],
        tags=["geladeira consul", "consul 410", "consul frost free"],
    ),
    TopProduct(
        model="Aspirador Robô Xiaomi Mi Robot",
        category="eletrodomestico",
        rank=4,
        source_label="Mercado Livre (2025)",
        price_from_brl=800,
        price_to_brl=2500,
        key_specs=["Robô", "Mapeamento", "Wi-Fi", "App"],
        tags=["robo aspirador xiaomi", "mi robot", "aspirador robo"],
    ),
]

# ─── IMPRESSORAS 3D ─────────────────────────────────────────────────────
PRINTERS_3D: list[TopProduct] = [
    TopProduct(
        model="Bambu Lab A1",
        category="3d_printer",
        rank=1,
        source_label="Levantamento Brasil (2025/2026)",
        price_from_brl=2700,
        price_to_brl=5600,
        key_specs=["LiDAR/autocalibração", "Wi-Fi", "Silenciosa", "Volume 256^3"],
        tags=["bambu lab a1", "bambu a1", "a1", "impressora 3d", "3d printer"],
    ),
    TopProduct(
        model="Bambu Lab A1 Mini",
        category="3d_printer",
        rank=2,
        source_label="Levantamento Brasil (2025/2026)",
        price_from_brl=2000,
        price_to_brl=4200,
        key_specs=["Compacta", "LiDAR/autocalibração", "Wi-Fi", "Volume 180^3"],
        tags=["bambu lab a1 mini", "a1 mini", "bambu a1 mini", "impressora 3d", "3d printer"],
    ),
    TopProduct(
        model="Bambu Lab P1S",
        category="3d_printer",
        rank=3,
        source_label="Levantamento Brasil (2025)",
        price_from_brl=7000,
        price_to_brl=13000,
        key_specs=["Alta velocidade", "Autonivelamento", "Câmera", "AMS compatível"],
        tags=["bambu lab p1s", "p1s", "p1 s", "bambu p1s", "impressora 3d", "3d printer"],
    ),
    TopProduct(
        model="Bambu Lab X1 Carbon",
        category="3d_printer",
        rank=4,
        source_label="Levantamento Brasil (2025)",
        price_from_brl=7700,
        price_to_brl=14000,
        key_specs=["Topo de linha", "AMS (combo)", "Câmera", "Alta precisão"],
        tags=["bambu lab x1 carbon", "x1 carbon", "x1", "carbon", "impressora 3d", "3d printer"],
    ),
]

# ─── CATÁLOGO UNIFICADO ───────────────────────────────────────────────────────
ALL_PRODUCTS: list[TopProduct] = (
    PHONES + TVS + NOTEBOOKS + AUDIO + GAMES + SNEAKERS + APPLIANCES + PRINTERS_3D
)
